# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Vincent Lewis
title: Web Developer
email: vincent.sean.lewis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creating software blends my love of learning, technology and creative problem solving.
  My professional experiences have taught me to work effectively as a member of a team to solve
  challenging and technical problems. My academic pursuits have given me the foundation for continued
  self study, gradually and perpetually becoming a better programmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
photoUrl: https://s3-us-west-1.amazonaws.com/vl-photos/ProfessionalPhoto/propic.jpeg
#twitter_username: jekyllrb
github_username:  vlewisGH

# Build settings
markdown: kramdown
